// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwedoxfmlunckcwiffap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3ZWRveGZtbHVuY2tjd2lmZmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2MzYwODAsImV4cCI6MjEwMzIxMjA4MH0.N8Cdm3g0kEYXhMKKIuPO3qlm0zVEPcVcn_UQI_qP9tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});